### PR TITLE
bugFix:account_format_in_different_networks

### PR DESCRIPTION
**Pull request by isunaslabs**
-Updated moment js time formatting
-updated endpoints
-added account formatting library

### CODE REVIEW

**Comment by isunaslabs** [comment]
Migration works well in both Pangolin and Pangoro

**Comment by 1022ranji** [comment]
Pangoro 地址和 pangolin 地址看起来都是5开头的？

https://user-images.githubusercontent.com/80877629/223009582-db289197-e263-44c2-a441-1ad5965bfd04.mov

**Comment by isunaslabs** [comment]
@1022ranji Should the address that the user is seeing on the UI also be changed to match the connected network?

**Comment by isunaslabs** [comment]
@1022ranji and @wuminzhe please review the last build. Thank you for your time

**Review by 1022ranji — APPROVED** [review]

**Comment by isunaslabs** [comment]
@wuminzhe I'm going to merge this PR to the main branch

**Pull request merged**
