### PR TITLE
Feat:crab-going-live-preparations

### PR DESCRIPTION
**Pull request by isunaslabs**
Added crab network

### CODE REVIEW

**Comment by isunaslabs** [comment]
@1022ranji  and @wuminzhe account migration on Crab is ready for testing, since it's using the dev net, don't forget to ALLOW INSECURE CONTENT on your chrome

**Comment by isunaslabs** [comment]
@1022ranji the last build has fixed the menu options order

**Comment by wuminzhe** [comment]
not switch to Crab Dev after connect to my metamask

**Comment by isunaslabs** [comment]
Account migration has nothing to do with Metamask, it is connected to Polkadot

**Comment by wuminzhe** [comment]
my mistake

**Comment by isunaslabs** [comment]
No worries mate.....

**Comment by isunaslabs** [comment]
@1022ranji  the last code build contains the multi wallet support and also has fixed the darwinia staking link issue

**Comment by isunaslabs** [comment]
@1022ranji  and @wuminzhe  check the last PR, I changed the Crab environmment to livenet. If it's all good then we should merge this to the main branch.

**Review by wuminzhe — APPROVED** [review]

**Pull request merged**
